---
# Source: data-space-connector/templates/marketplace-env-var-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: marketplace-secret-env
  namespace: "consumer"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: consumer
    app.kubernetes.io/managed-by: Helm
data:
  MONGO_BAE_BELP_PW: "T2Q0YmpyZ3RzcEpMYmQxcHpTSGFHanpBVEYzUjI2"
  MONGO_BAE_CHARGING_PW: "RW91RlQ0a2FRNUoydkV3NEZVSGJvUmplUFdBeE4w"
