---
# Source: data-space-connector/templates/data-plane-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: data-service-secret
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
data:
  postgres-user-password: "UkFHTlYzZkJGTzRYV1JZdmF6RDI2c21BcUw3b2k4"
  postgres-admin-password: "QzZDeVVYMFI0dFQxVmM2UDZYc1JiRWZKWkg0ZTNN"
