---
# Source: data-space-connector/templates/marketplace-env-var-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: marketplace-secret-env
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
data:
  MONGO_BAE_BELP_PW: "REk5QkxXc2dFVUc3SVRJbnkzeDJWUTdIRTFwcXNp"
  MONGO_BAE_CHARGING_PW: "NVpUWGthdW9RczJoUDhmUHpHY3owd0hUOElFMGlp"
