---
# Source: data-space-connector/templates/marketplace-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: marketplace-secret
  namespace: "provider"
  labels:
    
    app.kubernetes.io/name: data-space-connector
    helm.sh/chart: data-space-connector-8.2.20
    app.kubernetes.io/instance: provider
    app.kubernetes.io/managed-by: Helm
data:
  mongodb-root-password: "S0cyVEpzb2xMTmV3ZTk5YkpGNzdUQW52bFZnZDR0"
  mongodb-password: "bEdqSmJWNEk3Y0dMc09BZ3FDcE5ObkU2OU9URmlP"
